name: Semgrep SAST

on: push

permissions:
  contents: read

jobs:
  semgrep:
    name: runs Semgrep SAST
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: checks out source code
        uses: actions/checkout@v4

      - name: runs Semgrep scan
        run: semgrep scan --config auto .